import type { ExtensionSettings } from "./types";

export const LANGUAGES_BY_EXTENSION: Record<string, string> = {
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  tsx: "typescript",
  json: "json",
  css: "css",
  scss: "scss",
  less: "less",
  html: "html",
  htm: "html",
  xml: "xml",
  svg: "xml",
  py: "python",
  pyi: "python",
  pyw: "python",
  md: "markdown",
  mdx: "markdown",
  go: "go",
  rs: "rust",
  sql: "sql",
  yml: "yaml",
  yaml: "yaml",
  toml: "toml",
  rb: "ruby",
  lua: "lua",
  zig: "zig",
  dart: "dart",
};

export const EXTENSION_MAP = LANGUAGES_BY_EXTENSION;

export const EXTENSIONS_BY_LANGUAGE: Record<string, string> = {
  javascript: "js",
  typescript: "ts",
  json: "json",
  css: "css",
  scss: "scss",
  less: "less",
  html: "html",
  xml: "xml",
  python: "py",
  markdown: "md",
  go: "go",
  rust: "rs",
  sql: "sql",
  yaml: "yml",
  toml: "toml",
  ruby: "rb",
  lua: "lua",
  zig: "zig",
  dart: "dart",
};

export const ELEMENT_IDS = {
  RENDERER: "code-formatter-renderer",
  TOOLBAR: "code-formatter-toolbar",
  BUTTON_THEME: "code-formatter-toolbar-button-theme",
  BUTTON_COLLAPSE: "code-formatter-toolbar-button-collapse",
  BUTTON_EXPAND: "code-formatter-toolbar-button-expand",
  BUTTON_SEARCH: "code-formatter-toolbar-button-search",
  BUTTON_SWITCH: "code-formatter-switcher-button",
  BUTTON_COPY: "code-formatter-toolbar-button-copy",
  BUTTON_DOWNLOAD: "code-formatter-toolbar-button-download",
  BUTTON_OPEN_FILE: "code-formatter-toolbar-button-open-file",
  STATUS_BAR: "code-formatter-status-bar",
  DROP_ZONE: "code-formatter-drop-zone",
  FILE_INPUT: "code-formatter-file-input",
} as const;

export const CSS_CLASSES = {
  TOOLBAR: "code-formatter-toolbar",
  TOOLBAR_BUTTON: "code-formatter-toolbar__button",
  TOOLBAR_SEPARATOR: "code-formatter-toolbar__separator",
  TOOLBAR_SELECT: "code-formatter-toolbar__select",
  LOADED: "code-formatter-is-loaded",
  STATUS_BAR: "code-formatter-status-bar",
  STATUS_BAR_ITEM: "code-formatter-status-bar__item",
  STATUS_BAR_FILENAME: "code-formatter-status-bar__filename",
  SKELETON: "code-formatter-skeleton",
  SKELETON_LINE: "code-formatter-skeleton__line",
  DROP_ZONE: "code-formatter-drop-zone",
  DROP_ZONE_ACTIVE: "code-formatter-drop-zone--active",
  DROP_ZONE_DRAGOVER: "code-formatter-drop-zone--dragover",
} as const;

export const COLORS = {
  ACTIVE: "#73c991",
  INACTIVE: "#5a5a5a",
  EDITOR_BG_LIGHT: "#ffffff",
  EDITOR_BG_DARK: "#282c34",
  EDITOR_FG_LIGHT: "#24292e",
  EDITOR_FG_DARK: "#abb2bf",
  GUTTER_BG_LIGHT: "#f6f8fa",
  GUTTER_BG_DARK: "#21252b",
  GUTTER_FG_LIGHT: "#6a737d",
  GUTTER_FG_DARK: "#636d83",
} as const;

export const AVAILABLE_THEMES = [
  { value: "one-dark-pro", label: "One Dark Pro" },
  { value: "dracula", label: "Dracula" },
  { value: "nord", label: "Nord" },
  { value: "monokai", label: "Monokai" },
  { value: "material", label: "Material" },
  { value: "github-dark", label: "GitHub Dark" },
  { value: "github-light", label: "GitHub Light" },
  { value: "solarized-dark", label: "Solarized Dark" },
  { value: "solarized-light", label: "Solarized Light" },
  { value: "tokyo-night", label: "Tokyo Night" },
] as const;

export const PERFORMANCE_THRESHOLDS = {
  LARGE_FILE_LINES: 10000,
  HUGE_FILE_LINES: 50000,
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  CHUNK_SIZE: 5000,
} as const;

export const DEFAULT_SETTINGS: ExtensionSettings = {
  indentSize: 2,
  quoteStyle: "single",
  theme: "one-dark-pro",
  wrapLines: false,
  fontSize: "14",
  lineHeight: 1.6,
  useTabs: false,
  singleQuote: true,
  semi: true,
  trailingComma: "es5",
  e4x: false,
  spaceInEmptyParens: false,
  unescapeStrings: false,
  keepArrayIndentation: false,
  quoteStyleWasm: "preserve",
  keywordCase: "preserve",
  commaPosition: "before",
  autoFormatOnType: false,
  formatOnPasteMinLength: 5,
};

export const LANGUAGE_DEFAULTS: Record<
  string,
  { indentSize: number; useTabs: boolean; singleQuote: boolean; semi: boolean }
> = {
  javascript: { indentSize: 2, useTabs: false, singleQuote: true, semi: true },
  typescript: { indentSize: 2, useTabs: false, singleQuote: true, semi: true },
  python: { indentSize: 4, useTabs: false, singleQuote: true, semi: true },
  go: { indentSize: 4, useTabs: true, singleQuote: true, semi: true },
  java: { indentSize: 4, useTabs: false, singleQuote: false, semi: true },
  css: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  html: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  json: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  rust: { indentSize: 4, useTabs: false, singleQuote: true, semi: true },
  sql: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  yaml: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  toml: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
  markdown: { indentSize: 2, useTabs: false, singleQuote: false, semi: true },
};

export const FORMATTABLE_LANGUAGES = new Set([
  "javascript",
  "typescript",
  "json",
  "css",
  "scss",
  "html",
  "xml",
  "python",
  "go",
  "rust",
  "sql",
  "yaml",
  "toml",
  "ruby",
  "lua",
  "zig",
  "dart",
]);

export const CONTEXT_MENU_LANGUAGE_MAP: Record<string, string> = {
  formatJS: "javascript",
  formatTS: "typescript",
  formatCSS: "css",
  formatHTML: "html",
  formatJSON: "json",
  formatPython: "python",
  formatGo: "go",
  formatSQL: "sql",
  formatYAML: "yaml",
  formatTOML: "toml",
};
